
ButtonForgeSave = {
["AdvancedMode"] = true,
["AddonName"] = "Button Forge",
["ConfigureMode"] = false,
["RightClickSelfCast"] = false,
["Bars"] = {
{
["ButtonsLocked"] = false,
["VDriver"] = "",
["FlyoutDirection"] = "UP",
["Label"] = "",
["Order"] = 0,
["Rows"] = 4,
["Left"] = 1694.400024414063,
["Cols"] = 13,
["HVehicle"] = true,
["HSpec1"] = false,
["HBonusBar"] = true,
["KeyBindText"] = true,
["HSpec3"] = false,
["GridAlwaysOn"] = true,
["Buttons"] = {
{
["MacroName"] = "Auto Attack",
["MacroBody"] = "#showtooltip Auto Attack\n/startattack\n",
["Mode"] = "macro",
["KeyBinding"] = "HOME",
["MacroIndex"] = 11,
},
{
["MacroName"] = "stop",
["MacroBody"] = "/stopcasting\n",
["Mode"] = "macro",
["KeyBinding"] = "INSERT",
["MacroIndex"] = 44,
},
{
["MacroName"] = "player",
["MacroBody"] = "/focus player\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-F2",
["MacroIndex"] = 17,
},
{
["MacroName"] = "party1",
["MacroBody"] = "/focus  party1\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-F3",
["MacroIndex"] = 13,
},
{
["MacroName"] = "party2",
["MacroBody"] = "/focus party2\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-F5",
["MacroIndex"] = 14,
},
{
["MacroName"] = "party3",
["MacroBody"] = "/focus party3\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-F6",
["MacroIndex"] = 15,
},
{
["MacroName"] = "party4",
["MacroBody"] = "/focus party4\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-F7",
["MacroIndex"] = 16,
},
{
["MacroName"] = "raid1",
["MacroBody"] = "/focus raid1\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F1",
["MacroIndex"] = 19,
},
{
["MacroName"] = "raid2",
["MacroBody"] = "/focus raid2\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F2",
["MacroIndex"] = 30,
},
{
["MacroName"] = "raid3",
["MacroBody"] = "/focus raid3\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F3",
["MacroIndex"] = 37,
},
{
["MacroName"] = "raid4",
["MacroBody"] = "/focus raid4\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F4",
["MacroIndex"] = 38,
},
{
["MacroName"] = "raid5",
["MacroBody"] = "/focus raid5\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F5",
["MacroIndex"] = 39,
},
{
["MacroName"] = "raid6",
["MacroBody"] = "/focus raid6\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F6",
["MacroIndex"] = 40,
},
{
["MacroName"] = "raid7",
["MacroBody"] = "/focus raid7\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F7",
["MacroIndex"] = 41,
},
{
["MacroName"] = "raid8",
["MacroBody"] = "/focus raid8\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F8",
["MacroIndex"] = 42,
},
{
["MacroName"] = "raid9",
["MacroBody"] = "/focus raid9\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F9",
["MacroIndex"] = 43,
},
{
["MacroName"] = "raid10",
["MacroBody"] = "/focus raid10\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F10",
["MacroIndex"] = 20,
},
{
["MacroName"] = "raid11",
["MacroBody"] = "/focus raid11\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F11",
["MacroIndex"] = 21,
},
{
["MacroName"] = "raid12",
["MacroBody"] = "/focus raid12\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-F12",
["MacroIndex"] = 22,
},
{
["MacroName"] = "raid13",
["MacroBody"] = "/focus raid13\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F1",
["MacroIndex"] = 23,
},
{
["MacroName"] = "raid14",
["MacroBody"] = "/focus raid14\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F2",
["MacroIndex"] = 24,
},
{
["MacroName"] = "raid15",
["MacroBody"] = "/focus raid15\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F3",
["MacroIndex"] = 25,
},
{
["MacroName"] = "raid16",
["MacroBody"] = "/focus raid16\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F4",
["MacroIndex"] = 26,
},
{
["MacroName"] = "raid17",
["MacroBody"] = "/focus raid17\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F5",
["MacroIndex"] = 27,
},
{
["MacroName"] = "raid18",
["MacroBody"] = "/focus raid18\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F6",
["MacroIndex"] = 28,
},
{
["MacroName"] = "raid19",
["MacroBody"] = "/focus raid19\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F7",
["MacroIndex"] = 29,
},
{
["MacroName"] = "raid20",
["MacroBody"] = "/focus raid20\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F8",
["MacroIndex"] = 31,
},
{
["MacroName"] = "raid21",
["MacroBody"] = "/focus raid21\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F9",
["MacroIndex"] = 32,
},
{
["MacroName"] = "raid22",
["MacroBody"] = "/focus raid22\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F10",
["MacroIndex"] = 33,
},
{
["MacroName"] = "raid23",
["MacroBody"] = "/focus raid23\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F11",
["MacroIndex"] = 34,
},
{
["MacroName"] = "raid24",
["MacroBody"] = "/focus raid24\n",
["Mode"] = "macro",
["KeyBinding"] = "SHIFT-F12",
["MacroIndex"] = 35,
},
{
["MacroName"] = "raid25",
["MacroBody"] = "/focus raid25\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-F1",
["MacroIndex"] = 36,
},
{
["MacroName"] = "arena1",
["MacroBody"] = "/focus arena1\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-F8",
["MacroIndex"] = 1,
},
{
["MacroName"] = "arena2",
["MacroBody"] = "/focus arena2\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-F9",
["MacroIndex"] = 2,
},
{
["MacroName"] = "arena3",
["MacroBody"] = "/focus arena3\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-F10",
["MacroIndex"] = 3,
},
{
["MacroName"] = "arena4",
["MacroBody"] = "/focus arena4\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-F11",
["MacroIndex"] = 4,
},
{
["MacroName"] = "arena5",
["MacroBody"] = "/focus arena5\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-SHIFT-F12",
["MacroIndex"] = 5,
},
{
["MacroName"] = "arenapet1",
["MacroBody"] = "/focus arenapet1\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-SHIFT-F1",
["MacroIndex"] = 6,
},
{
["MacroName"] = "arenapet2",
["MacroBody"] = "/focus arenapet2\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-SHIFT-F2",
["MacroIndex"] = 7,
},
{
["MacroName"] = "arenapet3",
["MacroBody"] = "/focus arenapet3\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-SHIFT-F3",
["MacroIndex"] = 8,
},
{
["MacroName"] = "arenapet4",
["MacroBody"] = "/focus arenapet4\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-SHIFT-F4",
["MacroIndex"] = 9,
},
{
["MacroName"] = "arenapet5",
["MacroBody"] = "/focus arenapet5\n",
["Mode"] = "macro",
["KeyBinding"] = "CTRL-SHIFT-F5",
["MacroIndex"] = 10,
},
{
["MacroName"] = "clearfocus",
["MacroBody"] = "/clearfocus\n",
["Mode"] = "macro",
["KeyBinding"] = "DELETE",
["MacroIndex"] = 12,
},
{
["MacroName"] = "thred1",
["MacroBody"] = "/run  run_thread1()\n",
["Mode"] = "macro",
["KeyBinding"] = "NUMPAD1",
["MacroIndex"] = 48,
},
{
["MacroName"] = "thread2",
["MacroBody"] = "/run  run_thread2()\n",
["Mode"] = "macro",
["KeyBinding"] = "NUMPAD2",
["MacroIndex"] = 45,
},
{
["MacroName"] = "thread3",
["MacroBody"] = "/run run_thread3()\n",
["Mode"] = "macro",
["KeyBinding"] = "NUMPAD3",
["MacroIndex"] = 46,
},
{
["MacroName"] = "thread4",
["MacroBody"] = "/run  run_thread4()\n",
["Mode"] = "macro",
["KeyBinding"] = "NUMPAD5",
["MacroIndex"] = 47,
},
{
["MacroName"] = "racials",
["MacroBody"] = "/cast Shadowmeld\n/cast Blood Fury\n/cast Arcane Torrent\n/cast Berserking\n/cast Will to Survive\n",
["Mode"] = "macro",
["KeyBinding"] = "ALT-SHIFT-F1",
["MacroIndex"] = 18,
},
{
},
{
},
{
},
{
},
},
["Top"] = 287.0542297363281,
["BonusBar"] = false,
["Alpha"] = 1,
["HSpec4"] = false,
["HSpec2"] = false,
["GUI"] = true,
["Scale"] = 0.2,
["MacroText"] = true,
["TooltipsOn"] = true,
["HPetBattle"] = true,
["ButtonGap"] = 2,
["Enabled"] = true,
},
{
["ButtonsLocked"] = false,
["VDriver"] = "",
["FlyoutDirection"] = "UP",
["Label"] = "",
["Order"] = 1,
["Rows"] = 3,
["Left"] = 1694.400146484375,
["Cols"] = 15,
["HVehicle"] = true,
["HSpec1"] = false,
["HBonusBar"] = true,
["KeyBindText"] = true,
["HSpec3"] = false,
["Buttons"] = {
{
["KeyBinding"] = "CTRL-Y",
},
{
["KeyBinding"] = "CTRL-U",
},
{
["KeyBinding"] = "CTRL-I",
},
{
["KeyBinding"] = "CTRL-O",
},
{
["KeyBinding"] = "CTRL-P",
},
{
["KeyBinding"] = "CTRL-J",
},
{
["KeyBinding"] = "CTRL-K",
},
{
["KeyBinding"] = "CTRL-L",
},
{
["KeyBinding"] = "CTRL-N",
},
{
["KeyBinding"] = "CTRL-M",
},
{
["KeyBinding"] = "CTRL-6",
},
{
["KeyBinding"] = "CTRL-7",
},
{
["KeyBinding"] = "CTRL-8",
},
{
["KeyBinding"] = "CTRL-9",
},
{
["KeyBinding"] = "CTRL-0",
},
{
["KeyBinding"] = "SHIFT-Y",
},
{
["KeyBinding"] = "SHIFT-U",
},
{
["KeyBinding"] = "SHIFT-I",
},
{
["KeyBinding"] = "SHIFT-O",
},
{
["KeyBinding"] = "SHIFT-P",
},
{
["KeyBinding"] = "SHIFT-J",
},
{
["KeyBinding"] = "SHIFT-K",
},
{
["KeyBinding"] = "SHIFT-L",
},
{
["KeyBinding"] = "SHIFT-N",
},
{
["KeyBinding"] = "SHIFT-M",
},
{
["KeyBinding"] = "SHIFT-6",
},
{
["KeyBinding"] = "SHIFT-7",
},
{
["KeyBinding"] = "SHIFT-8",
},
{
["KeyBinding"] = "SHIFT-9",
},
{
["KeyBinding"] = "SHIFT-0",
},
{
["KeyBinding"] = "ALT-Y",
},
{
["KeyBinding"] = "ALT-U",
},
{
["KeyBinding"] = "ALT-I",
},
{
["KeyBinding"] = "ALT-O",
},
{
["KeyBinding"] = "ALT-P",
},
{
["KeyBinding"] = "ALT-J",
},
{
["KeyBinding"] = "ALT-K",
},
{
["KeyBinding"] = "ALT-L",
},
{
["KeyBinding"] = "ALT-N",
},
{
["KeyBinding"] = "ALT-M",
},
{
["KeyBinding"] = "ALT-6",
},
{
["KeyBinding"] = "ALT-7",
},
{
["KeyBinding"] = "ALT-8",
},
{
["KeyBinding"] = "ALT-9",
},
{
["KeyBinding"] = "ALT-0",
},
},
["GridAlwaysOn"] = true,
["Top"] = 249.4542694091797,
["BonusBar"] = false,
["Alpha"] = 1,
["HSpec4"] = false,
["HSpec2"] = false,
["GUI"] = true,
["Scale"] = 0.2,
["HPetBattle"] = true,
["TooltipsOn"] = true,
["MacroText"] = true,
["ButtonGap"] = 2,
["Enabled"] = true,
},
},
["Version"] = 1.3,
["VersionMinor"] = 0.2,
}
BFSave = nil
