
OliaEyes_Export = {
{
["type"] = "Static",
["key"] = "NUMPAD1",
["id"] = "Thread 1",
["class"] = "GLOBAL",
["color"] = "1e620a",
},
{
["type"] = "Static",
["key"] = "NUMPAD2",
["id"] = "Thread 2",
["class"] = "GLOBAL",
["color"] = "1f180a",
},
{
["type"] = "Static",
["key"] = "NUMPAD3",
["id"] = "Thread 3",
["class"] = "GLOBAL",
["color"] = "1f320a",
},
{
["type"] = "Static",
["key"] = "NUMPAD4",
["id"] = "Thread 4",
["class"] = "GLOBAL",
["color"] = "1f4c0a",
},
{
["type"] = "Static",
["key"] = "NUMPAD5",
["id"] = "Thread 5",
["class"] = "GLOBAL",
["color"] = "1f020a",
},
{
["type"] = "Static",
["key"] = "NUMPAD6",
["id"] = "Thread 6",
["class"] = "GLOBAL",
["color"] = "1f1c0a",
},
{
["type"] = "Static",
["key"] = "ALT-F1",
["id"] = "Attack",
["class"] = "GLOBAL",
["color"] = "200d0a",
},
{
["type"] = "Static",
["key"] = "ALT-F2",
["id"] = "Stopcasting",
["class"] = "GLOBAL",
["color"] = "3e4f09",
},
{
["type"] = "Static",
["key"] = "ALT-F3",
["id"] = "ClearFocus",
["class"] = "GLOBAL",
["color"] = "16410a",
},
{
["type"] = "Static",
["key"] = "ALT-F5",
["id"] = "player",
["class"] = "GLOBAL",
["color"] = "24150a",
},
{
["type"] = "Static",
["key"] = "ALT-F6",
["id"] = "target",
["class"] = "GLOBAL",
["color"] = "0d390a",
},
{
["type"] = "Static",
["key"] = "ALT-F7",
["id"] = "targettarget",
["class"] = "GLOBAL",
["color"] = "22010a",
},
{
["type"] = "Static",
["key"] = "ALT-F8",
["id"] = "mouseover",
["class"] = "GLOBAL",
["color"] = "382e09",
},
{
["type"] = "Static",
["key"] = "ALT-F9",
["id"] = "pettarget",
["class"] = "GLOBAL",
["color"] = "113709",
},
{
["type"] = "Static",
["key"] = "ALT-F10",
["id"] = "focus",
["class"] = "GLOBAL",
["color"] = "260d0a",
},
{
["type"] = "Static",
["key"] = "ALT-F11",
["id"] = "pet",
["class"] = "GLOBAL",
["color"] = "1f1b0a",
},
{
["type"] = "Static",
["key"] = "ALT-F12",
["id"] = "party1",
["class"] = "GLOBAL",
["color"] = "241e0a",
},
{
["type"] = "Static",
["key"] = "ALT-INSERT",
["id"] = "party2",
["class"] = "GLOBAL",
["color"] = "245e0a",
},
{
["type"] = "Static",
["key"] = "ALT-DELETE",
["id"] = "party3",
["class"] = "GLOBAL",
["color"] = "243a0a",
},
{
["type"] = "Static",
["key"] = "ALT-HOME",
["id"] = "party4",
["class"] = "GLOBAL",
["color"] = "24160a",
},
{
["type"] = "Static",
["key"] = "ALT-END",
["id"] = "arena1",
["class"] = "GLOBAL",
["color"] = "273a0a",
},
{
["type"] = "Static",
["key"] = "ALT-PAGEUP",
["id"] = "arena2",
["class"] = "GLOBAL",
["color"] = "27160a",
},
{
["type"] = "Static",
["key"] = "ALT-PAGEDOWN",
["id"] = "arena3",
["class"] = "GLOBAL",
["color"] = "27560a",
},
{
["type"] = "Static",
["key"] = "ALT-UP",
["id"] = "arena4",
["class"] = "GLOBAL",
["color"] = "27320a",
},
{
["type"] = "Static",
["key"] = "ALT-DOWN",
["id"] = "arena5",
["class"] = "GLOBAL",
["color"] = "280e0a",
},
{
["type"] = "Static",
["key"] = "ALT-LEFT",
["id"] = "raid1",
["class"] = "GLOBAL",
["color"] = "0e110a",
},
{
["type"] = "Static",
["key"] = "ALT-RIGHT",
["id"] = "raid2",
["class"] = "GLOBAL",
["color"] = "0e2b0a",
},
{
["type"] = "Static",
["key"] = "ALT-MINUS",
["id"] = "raid3",
["class"] = "GLOBAL",
["color"] = "0e450a",
},
{
["type"] = "Static",
["key"] = "ALT-EQUALS",
["id"] = "raid4",
["class"] = "GLOBAL",
["color"] = "0e5f0a",
},
{
["type"] = "Static",
["key"] = "ALT-SPACE",
["id"] = "raid5",
["class"] = "GLOBAL",
["color"] = "0e150a",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F1",
["id"] = "raid6",
["class"] = "GLOBAL",
["color"] = "0e2f0a",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F2",
["id"] = "raid7",
["class"] = "GLOBAL",
["color"] = "0f490a",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F3",
["id"] = "raid8",
["class"] = "GLOBAL",
["color"] = "0f630a",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F4",
["id"] = "raid9",
["class"] = "GLOBAL",
["color"] = "0f190a",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F5",
["id"] = "raid10",
["class"] = "GLOBAL",
["color"] = "3f2909",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F6",
["id"] = "raid11",
["class"] = "GLOBAL",
["color"] = "3f0509",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F7",
["id"] = "raid12",
["class"] = "GLOBAL",
["color"] = "404509",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F8",
["id"] = "raid13",
["class"] = "GLOBAL",
["color"] = "402109",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F9",
["id"] = "raid14",
["class"] = "GLOBAL",
["color"] = "406109",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F10",
["id"] = "raid15",
["class"] = "GLOBAL",
["color"] = "413d09",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F11",
["id"] = "raid16",
["class"] = "GLOBAL",
["color"] = "411909",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-F12",
["id"] = "raid17",
["class"] = "GLOBAL",
["color"] = "425909",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-INSERT",
["id"] = "raid18",
["class"] = "GLOBAL",
["color"] = "423509",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-DELETE",
["id"] = "raid19",
["class"] = "GLOBAL",
["color"] = "421109",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-HOME",
["id"] = "raid20",
["class"] = "GLOBAL",
["color"] = "404309",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-END",
["id"] = "raid21",
["class"] = "GLOBAL",
["color"] = "401f09",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-PAGEUP",
["id"] = "raid22",
["class"] = "GLOBAL",
["color"] = "415f09",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-PAGEDOWN",
["id"] = "raid23",
["class"] = "GLOBAL",
["color"] = "413b09",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-UP",
["id"] = "raid24",
["class"] = "GLOBAL",
["color"] = "411709",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-DOWN",
["id"] = "raid25",
["class"] = "GLOBAL",
["color"] = "425709",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-LEFT",
["id"] = "raid26",
["class"] = "GLOBAL",
["color"] = "423309",
},
{
["type"] = "Static",
["key"] = "CTRL-SHIFT-RIGHT",
["id"] = "raid27",
["class"] = "GLOBAL",
["color"] = "420f09",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F1",
["id"] = "raid28",
["class"] = "GLOBAL",
["color"] = "434f09",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F2",
["id"] = "raid29",
["class"] = "GLOBAL",
["color"] = "432b09",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F3",
["id"] = "raid30",
["class"] = "GLOBAL",
["color"] = "415d09",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F4",
["id"] = "raid31",
["class"] = "GLOBAL",
["color"] = "413909",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F5",
["id"] = "raid32",
["class"] = "GLOBAL",
["color"] = "411509",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F6",
["id"] = "raid33",
["class"] = "GLOBAL",
["color"] = "425509",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F7",
["id"] = "raid34",
["class"] = "GLOBAL",
["color"] = "423109",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F8",
["id"] = "raid35",
["class"] = "GLOBAL",
["color"] = "430d09",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F9",
["id"] = "raid36",
["class"] = "GLOBAL",
["color"] = "434d09",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F10",
["id"] = "raid37",
["class"] = "GLOBAL",
["color"] = "432909",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F11",
["id"] = "raid38",
["class"] = "GLOBAL",
["color"] = "440509",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-F12",
["id"] = "raid39",
["class"] = "GLOBAL",
["color"] = "444509",
},
{
["type"] = "Static",
["key"] = "ALT-SHIFT-INSERT",
["id"] = "raid40",
["class"] = "GLOBAL",
["color"] = "411309",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F1",
["id"] = "Steady Shot",
["class"] = "HUNTER",
["color"] = "2a570a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F2",
["id"] = "Auto Shot",
["class"] = "HUNTER",
["color"] = "19170a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F3",
["id"] = "Arcane Shot",
["class"] = "HUNTER",
["color"] = "510f09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F4",
["id"] = "Aimed Shot",
["class"] = "HUNTER",
["color"] = "18180a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F5",
["id"] = "Multi-Shot",
["class"] = "HUNTER",
["color"] = "323c09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F6",
["id"] = "Serpent Sting",
["class"] = "HUNTER",
["color"] = "284d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F7",
["id"] = "Viper Sting",
["class"] = "HUNTER",
["color"] = "15370a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F8",
["id"] = "Scorpid Sting",
["class"] = "HUNTER",
["color"] = "0b170a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F9",
["id"] = "Kill Command",
["class"] = "HUNTER",
["color"] = "0f230a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F10",
["id"] = "Bestial Wrath",
["class"] = "HUNTER",
["color"] = "0e370a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F11",
["id"] = "Intimidation",
["class"] = "HUNTER",
["color"] = "341109",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F12",
["id"] = "Scatter Shot",
["class"] = "HUNTER",
["color"] = "505109",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-INSERT",
["id"] = "Silencing Shot",
["class"] = "HUNTER",
["color"] = "110a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DELETE",
["id"] = "Wyvern Sting",
["class"] = "HUNTER",
["color"] = "24460a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-HOME",
["id"] = "Feign Death",
["class"] = "HUNTER",
["color"] = "1c080a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-END",
["id"] = "Freezing Trap",
["class"] = "HUNTER",
["color"] = "493709",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEUP",
["id"] = "Frost Trap",
["class"] = "HUNTER",
["color"] = "1d620a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEDOWN",
["id"] = "Explosive Trap",
["class"] = "HUNTER",
["color"] = "26510a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-UP",
["id"] = "Snake Trap",
["class"] = "HUNTER",
["color"] = "584909",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DOWN",
["id"] = "Hunter's Mark",
["class"] = "HUNTER",
["color"] = "235d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-LEFT",
["id"] = "Flare",
["class"] = "HUNTER",
["color"] = "362e09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-RIGHT",
["id"] = "Aspect of the Hawk",
["class"] = "HUNTER",
["color"] = "252b0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-MINUS",
["id"] = "Aspect of the Viper",
["class"] = "HUNTER",
["color"] = "15380a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-EQUALS",
["id"] = "Aspect of the Cheetah",
["class"] = "HUNTER",
["color"] = "0c4b0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-SPACE",
["id"] = "Aspect of the Pack",
["class"] = "HUNTER",
["color"] = "1a030a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F1",
["id"] = "Mortal Strike",
["class"] = "WARRIOR",
["color"] = "27590a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F2",
["id"] = "Bloodthirst",
["class"] = "WARRIOR",
["color"] = "0a440a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F3",
["id"] = "Shield Slam",
["class"] = "WARRIOR",
["color"] = "0e4d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F4",
["id"] = "Execute",
["class"] = "WARRIOR",
["color"] = "5a2b09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F5",
["id"] = "Overpower",
["class"] = "WARRIOR",
["color"] = "0e2e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F6",
["id"] = "Whirlwind",
["class"] = "WARRIOR",
["color"] = "164f0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F7",
["id"] = "Heroic Strike",
["class"] = "WARRIOR",
["color"] = "1a440a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F8",
["id"] = "Cleave",
["class"] = "WARRIOR",
["color"] = "582209",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F9",
["id"] = "Devastate",
["class"] = "WARRIOR",
["color"] = "0e5c0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F10",
["id"] = "Sunder Armor",
["class"] = "WARRIOR",
["color"] = "265a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F11",
["id"] = "Revenge",
["class"] = "WARRIOR",
["color"] = "201a09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F12",
["id"] = "Charge",
["class"] = "WARRIOR",
["color"] = "1f5b0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-INSERT",
["id"] = "Intercept",
["class"] = "WARRIOR",
["color"] = "252009",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DELETE",
["id"] = "Intervene",
["class"] = "WARRIOR",
["color"] = "0d4e09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-HOME",
["id"] = "Pummel",
["class"] = "WARRIOR",
["color"] = "18440a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-END",
["id"] = "Shield Bash",
["class"] = "WARRIOR",
["color"] = "21020a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEUP",
["id"] = "Disarm",
["class"] = "WARRIOR",
["color"] = "29490a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEDOWN",
["id"] = "Intimidating Shout",
["class"] = "WARRIOR",
["color"] = "155b0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-UP",
["id"] = "Battle Shout",
["class"] = "WARRIOR",
["color"] = "264c0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DOWN",
["id"] = "Commanding Shout",
["class"] = "WARRIOR",
["color"] = "2f5a09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-LEFT",
["id"] = "Demoralizing Shout",
["class"] = "WARRIOR",
["color"] = "1f510a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-RIGHT",
["id"] = "Spell Reflection",
["class"] = "WARRIOR",
["color"] = "17220a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F1",
["id"] = "Lightning Bolt",
["class"] = "SHAMAN",
["color"] = "234b0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F2",
["id"] = "Chain Lightning",
["class"] = "SHAMAN",
["color"] = "4e4f09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F3",
["id"] = "Earth Shock",
["class"] = "SHAMAN",
["color"] = "204d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F4",
["id"] = "Frost Shock",
["class"] = "SHAMAN",
["color"] = "2a570a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F5",
["id"] = "Flame Shock",
["class"] = "SHAMAN",
["color"] = "16380a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F6",
["id"] = "Lesser Healing Wave",
["class"] = "SHAMAN",
["color"] = "1f1a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F7",
["id"] = "Healing Wave",
["class"] = "SHAMAN",
["color"] = "4c2d09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F8",
["id"] = "Chain Heal",
["class"] = "SHAMAN",
["color"] = "145e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F9",
["id"] = "Earth Shield",
["class"] = "SHAMAN",
["color"] = "22540a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F10",
["id"] = "Water Shield",
["class"] = "SHAMAN",
["color"] = "280f0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F11",
["id"] = "Lightning Shield",
["class"] = "SHAMAN",
["color"] = "0c280a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F12",
["id"] = "Stormstrike",
["class"] = "SHAMAN",
["color"] = "0f440a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-INSERT",
["id"] = "Shamanistic Rage",
["class"] = "SHAMAN",
["color"] = "170d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DELETE",
["id"] = "Purge",
["class"] = "SHAMAN",
["color"] = "134009",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-HOME",
["id"] = "Cure Poison",
["class"] = "SHAMAN",
["color"] = "2a1209",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-END",
["id"] = "Grounding Totem",
["class"] = "SHAMAN",
["color"] = "24070a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEUP",
["id"] = "Tremor Totem",
["class"] = "SHAMAN",
["color"] = "2c0409",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEDOWN",
["id"] = "Earthbind Totem",
["class"] = "SHAMAN",
["color"] = "1d3a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-UP",
["id"] = "Bloodlust",
["class"] = "SHAMAN",
["color"] = "23150a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DOWN",
["id"] = "Heroism",
["class"] = "SHAMAN",
["color"] = "0d5a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F1",
["id"] = "Frostbolt",
["class"] = "MAGE",
["color"] = "1f470a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F2",
["id"] = "Ice Lance",
["class"] = "MAGE",
["color"] = "1e270a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F3",
["id"] = "Cone of Cold",
["class"] = "MAGE",
["color"] = "26510a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F4",
["id"] = "Frost Nova",
["class"] = "MAGE",
["color"] = "17450a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F5",
["id"] = "Ice Block",
["class"] = "MAGE",
["color"] = "23530a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F6",
["id"] = "Icy Veins",
["class"] = "MAGE",
["color"] = "17440a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F7",
["id"] = "Summon Water Elemental",
["class"] = "MAGE",
["color"] = "125b0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F8",
["id"] = "Fireball",
["class"] = "MAGE",
["color"] = "2a310a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F9",
["id"] = "Pyroblast",
["class"] = "MAGE",
["color"] = "4c3a09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F10",
["id"] = "Scorch",
["class"] = "MAGE",
["color"] = "22140a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F11",
["id"] = "Fire Blast",
["class"] = "MAGE",
["color"] = "193e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F12",
["id"] = "Combustion",
["class"] = "MAGE",
["color"] = "281b0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-INSERT",
["id"] = "Dragon's Breath",
["class"] = "MAGE",
["color"] = "0d0c0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DELETE",
["id"] = "Blast Wave",
["class"] = "MAGE",
["color"] = "12380a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-HOME",
["id"] = "Arcane Blast",
["class"] = "MAGE",
["color"] = "13380a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-END",
["id"] = "Arcane Missiles",
["class"] = "MAGE",
["color"] = "21440a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEUP",
["id"] = "Arcane Explosion",
["class"] = "MAGE",
["color"] = "143e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEDOWN",
["id"] = "Counterspell",
["class"] = "MAGE",
["color"] = "540809",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-UP",
["id"] = "Spellsteal",
["class"] = "MAGE",
["color"] = "0d310a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DOWN",
["id"] = "Polymorph",
["class"] = "MAGE",
["color"] = "0e4f0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-LEFT",
["id"] = "Blink",
["class"] = "MAGE",
["color"] = "102a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-RIGHT",
["id"] = "Evocation",
["class"] = "MAGE",
["color"] = "100e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-MINUS",
["id"] = "Invisibility",
["class"] = "MAGE",
["color"] = "1f2a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-EQUALS",
["id"] = "Arcane Intellect",
["class"] = "MAGE",
["color"] = "103e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-SPACE",
["id"] = "Arcane Brilliance",
["class"] = "MAGE",
["color"] = "1f2d0a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F1",
["id"] = "Ice Armor",
["class"] = "MAGE",
["color"] = "21040a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F2",
["id"] = "Molten Armor",
["class"] = "MAGE",
["color"] = "395c08",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F3",
["id"] = "Mage Armor",
["class"] = "MAGE",
["color"] = "3c4609",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F1",
["id"] = "Flash Heal",
["class"] = "PRIEST",
["color"] = "20460a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F2",
["id"] = "Greater Heal",
["class"] = "PRIEST",
["color"] = "2a2009",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F3",
["id"] = "Renew",
["class"] = "PRIEST",
["color"] = "113b0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F4",
["id"] = "Power Word: Shield",
["class"] = "PRIEST",
["color"] = "1f330a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F5",
["id"] = "Prayer of Mending",
["class"] = "PRIEST",
["color"] = "11310a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F6",
["id"] = "Prayer of Healing",
["class"] = "PRIEST",
["color"] = "1e0c09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F7",
["id"] = "Circle of Healing",
["class"] = "PRIEST",
["color"] = "0f020a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F8",
["id"] = "Binding Heal",
["class"] = "PRIEST",
["color"] = "2a480a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F9",
["id"] = "Smite",
["class"] = "PRIEST",
["color"] = "5d5909",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F10",
["id"] = "Holy Fire",
["class"] = "PRIEST",
["color"] = "26590a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F11",
["id"] = "Shadow Word: Pain",
["class"] = "PRIEST",
["color"] = "1e240a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F12",
["id"] = "Mind Blast",
["class"] = "PRIEST",
["color"] = "23590a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-INSERT",
["id"] = "Mind Flay",
["class"] = "PRIEST",
["color"] = "20050a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DELETE",
["id"] = "Vampiric Touch",
["class"] = "PRIEST",
["color"] = "26610a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-HOME",
["id"] = "Shadow Word: Death",
["class"] = "PRIEST",
["color"] = "163b0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-END",
["id"] = "Devouring Plague",
["class"] = "PRIEST",
["color"] = "1f540a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEUP",
["id"] = "Dispel Magic",
["class"] = "PRIEST",
["color"] = "214d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEDOWN",
["id"] = "Mass Dispel",
["class"] = "PRIEST",
["color"] = "2a000a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-UP",
["id"] = "Cure Disease",
["class"] = "PRIEST",
["color"] = "23530a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DOWN",
["id"] = "Abolish Disease",
["class"] = "PRIEST",
["color"] = "1f160a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-LEFT",
["id"] = "Psychic Scream",
["class"] = "PRIEST",
["color"] = "23490a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-RIGHT",
["id"] = "Fade",
["class"] = "PRIEST",
["color"] = "22380a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-MINUS",
["id"] = "Shadowfiend",
["class"] = "PRIEST",
["color"] = "1f4b0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-EQUALS",
["id"] = "Power Infusion",
["class"] = "PRIEST",
["color"] = "131d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-SPACE",
["id"] = "Pain Suppression",
["class"] = "PRIEST",
["color"] = "275409",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F1",
["id"] = "Power Word: Fortitude",
["class"] = "PRIEST",
["color"] = "635309",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F2",
["id"] = "Prayer of Fortitude",
["class"] = "PRIEST",
["color"] = "413909",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F3",
["id"] = "Shadow Protection",
["class"] = "PRIEST",
["color"] = "171e0a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F4",
["id"] = "Prayer of Shadow Protection",
["class"] = "PRIEST",
["color"] = "263c0a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F5",
["id"] = "Inner Fire",
["class"] = "PRIEST",
["color"] = "2a0a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F1",
["id"] = "Curse of Agony",
["class"] = "WARLOCK",
["color"] = "5d5c09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F2",
["id"] = "Corruption",
["class"] = "WARLOCK",
["color"] = "11270a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F3",
["id"] = "Unstable Affliction",
["class"] = "WARLOCK",
["color"] = "1e4b0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F4",
["id"] = "Drain Life",
["class"] = "WARLOCK",
["color"] = "0a5d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F5",
["id"] = "Fear",
["class"] = "WARLOCK",
["color"] = "1e4309",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F6",
["id"] = "Howl of Terror",
["class"] = "WARLOCK",
["color"] = "0e400a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F7",
["id"] = "Death Coil",
["class"] = "WARLOCK",
["color"] = "0b500a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F8",
["id"] = "Curse of the Elements",
["class"] = "WARLOCK",
["color"] = "19320a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F9",
["id"] = "Curse of Tongues",
["class"] = "WARLOCK",
["color"] = "13240a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F10",
["id"] = "Seed of Corruption",
["class"] = "WARLOCK",
["color"] = "1d0d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F11",
["id"] = "Shadow Bolt",
["class"] = "WARLOCK",
["color"] = "1c400a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F12",
["id"] = "Immolate",
["class"] = "WARLOCK",
["color"] = "522e09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-INSERT",
["id"] = "Incinerate",
["class"] = "WARLOCK",
["color"] = "2a370a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DELETE",
["id"] = "Conflagrate",
["class"] = "WARLOCK",
["color"] = "0b500a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-HOME",
["id"] = "Searing Pain",
["class"] = "WARLOCK",
["color"] = "21210a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-END",
["id"] = "Shadowburn",
["class"] = "WARLOCK",
["color"] = "18280a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEUP",
["id"] = "Shadowfury",
["class"] = "WARLOCK",
["color"] = "321f09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEDOWN",
["id"] = "Demon Armor",
["class"] = "WARLOCK",
["color"] = "0d140a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-UP",
["id"] = "Fel Armor",
["class"] = "WARLOCK",
["color"] = "10390a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DOWN",
["id"] = "Soul Link",
["class"] = "WARLOCK",
["color"] = "19480a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-LEFT",
["id"] = "Summon Felhunter",
["class"] = "WARLOCK",
["color"] = "2d4409",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-RIGHT",
["id"] = "Summon Felguard",
["class"] = "WARLOCK",
["color"] = "0f070a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F1",
["id"] = "Lifebloom",
["class"] = "DRUID",
["color"] = "2c5f09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F2",
["id"] = "Rejuvenation",
["class"] = "DRUID",
["color"] = "22000a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F3",
["id"] = "Regrowth",
["class"] = "DRUID",
["color"] = "185e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F4",
["id"] = "Healing Touch",
["class"] = "DRUID",
["color"] = "20170a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F5",
["id"] = "Swiftmend",
["class"] = "DRUID",
["color"] = "1a490a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F6",
["id"] = "Moonfire",
["class"] = "DRUID",
["color"] = "202e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F7",
["id"] = "Insect Swarm",
["class"] = "DRUID",
["color"] = "374909",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F8",
["id"] = "Wrath",
["class"] = "DRUID",
["color"] = "152c0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F9",
["id"] = "Starfire",
["class"] = "DRUID",
["color"] = "1b510a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F10",
["id"] = "Entangling Roots",
["class"] = "DRUID",
["color"] = "2b2009",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F11",
["id"] = "Cyclone",
["class"] = "DRUID",
["color"] = "2a3a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F12",
["id"] = "Faerie Fire",
["class"] = "DRUID",
["color"] = "380009",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-INSERT",
["id"] = "Hibernate",
["class"] = "DRUID",
["color"] = "523d09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DELETE",
["id"] = "Innervate",
["class"] = "DRUID",
["color"] = "10160a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-HOME",
["id"] = "Barkskin",
["class"] = "DRUID",
["color"] = "2a3509",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-END",
["id"] = "Nature's Swiftness",
["class"] = "DRUID",
["color"] = "341a09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEUP",
["id"] = "Force of Nature",
["class"] = "DRUID",
["color"] = "28210a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEDOWN",
["id"] = "Mangle (Cat)",
["class"] = "DRUID",
["color"] = "23630a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-UP",
["id"] = "Shred",
["class"] = "DRUID",
["color"] = "240d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DOWN",
["id"] = "Rip",
["class"] = "DRUID",
["color"] = "1a550a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-LEFT",
["id"] = "Ferocious Bite",
["class"] = "DRUID",
["color"] = "145d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-RIGHT",
["id"] = "Rake",
["class"] = "DRUID",
["color"] = "1a5f0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-MINUS",
["id"] = "Pounce",
["class"] = "DRUID",
["color"] = "26210a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-EQUALS",
["id"] = "Mangle (Bear)",
["class"] = "DRUID",
["color"] = "205e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-SPACE",
["id"] = "Maul",
["class"] = "DRUID",
["color"] = "2a240a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F1",
["id"] = "Lacerate",
["class"] = "DRUID",
["color"] = "4f4208",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F2",
["id"] = "Swipe",
["class"] = "DRUID",
["color"] = "0c100a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F3",
["id"] = "Bash",
["class"] = "DRUID",
["color"] = "10580a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F4",
["id"] = "Feral Charge",
["class"] = "DRUID",
["color"] = "293a0a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F5",
["id"] = "Cat Form",
["class"] = "DRUID",
["color"] = "3e3b09",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F6",
["id"] = "Bear Form",
["class"] = "DRUID",
["color"] = "1b460a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F7",
["id"] = "Dire Bear Form",
["class"] = "DRUID",
["color"] = "1c0e08",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F8",
["id"] = "Travel Form",
["class"] = "DRUID",
["color"] = "241f0a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F9",
["id"] = "Moonkin Form",
["class"] = "DRUID",
["color"] = "27500a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F10",
["id"] = "Tree of Life",
["class"] = "DRUID",
["color"] = "574b09",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F11",
["id"] = "Mark of the Wild",
["class"] = "DRUID",
["color"] = "210009",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-F12",
["id"] = "Thorns",
["class"] = "DRUID",
["color"] = "0b350a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-INSERT",
["id"] = "Gift of the Wild",
["class"] = "DRUID",
["color"] = "585709",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-DELETE",
["id"] = "Omen of Clarity",
["class"] = "DRUID",
["color"] = "10610a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-HOME",
["id"] = "Remove Curse",
["class"] = "DRUID",
["color"] = "16040a",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-END",
["id"] = "Abolish Poison",
["class"] = "DRUID",
["color"] = "313908",
},
{
["type"] = "Dynamic",
["key"] = "SHIFT-PAGEUP",
["id"] = "Rebirth",
["class"] = "DRUID",
["color"] = "164a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F1",
["id"] = "Sinister Strike",
["class"] = "ROGUE",
["color"] = "1c200a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F2",
["id"] = "Eviscerate",
["class"] = "ROGUE",
["color"] = "0c260a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F3",
["id"] = "Kidney Shot",
["class"] = "ROGUE",
["color"] = "243f0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F4",
["id"] = "Cheap Shot",
["class"] = "ROGUE",
["color"] = "1c440a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F5",
["id"] = "Backstab",
["class"] = "ROGUE",
["color"] = "433d09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F6",
["id"] = "Ambush",
["class"] = "ROGUE",
["color"] = "5b4208",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F7",
["id"] = "Garrote",
["class"] = "ROGUE",
["color"] = "18430a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F8",
["id"] = "Rupture",
["class"] = "ROGUE",
["color"] = "19200a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F9",
["id"] = "Slice and Dice",
["class"] = "ROGUE",
["color"] = "14380a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F10",
["id"] = "Mutilate",
["class"] = "ROGUE",
["color"] = "231e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F11",
["id"] = "Hemorrage",
["class"] = "ROGUE",
["color"] = "235d0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F12",
["id"] = "Ghostly Strike",
["class"] = "ROGUE",
["color"] = "0e460a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-INSERT",
["id"] = "Shiv",
["class"] = "ROGUE",
["color"] = "2a1f0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DELETE",
["id"] = "Gouge",
["class"] = "ROGUE",
["color"] = "322b09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-HOME",
["id"] = "Blind",
["class"] = "ROGUE",
["color"] = "103c0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-END",
["id"] = "Kick",
["class"] = "ROGUE",
["color"] = "121f08",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEUP",
["id"] = "Cloak of Shadows",
["class"] = "ROGUE",
["color"] = "0b2c09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEDOWN",
["id"] = "Vanish",
["class"] = "ROGUE",
["color"] = "401b09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-UP",
["id"] = "Evasion",
["class"] = "ROGUE",
["color"] = "185a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DOWN",
["id"] = "Sprint",
["class"] = "ROGUE",
["color"] = "0d5509",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-LEFT",
["id"] = "Preparation",
["class"] = "ROGUE",
["color"] = "162f0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-RIGHT",
["id"] = "Shadowstep",
["class"] = "ROGUE",
["color"] = "13260a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F1",
["id"] = "Flash of Light",
["class"] = "PALADIN",
["color"] = "16620a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F2",
["id"] = "Holy Light",
["class"] = "PALADIN",
["color"] = "21240a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F3",
["id"] = "Holy Shock",
["class"] = "PALADIN",
["color"] = "0f5c0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F4",
["id"] = "Cleanse",
["class"] = "PALADIN",
["color"] = "1f3c0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F5",
["id"] = "Purify",
["class"] = "PALADIN",
["color"] = "283f0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F6",
["id"] = "Judgement",
["class"] = "PALADIN",
["color"] = "133a0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F7",
["id"] = "Consecration",
["class"] = "PALADIN",
["color"] = "240e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F8",
["id"] = "Hammer of Justice",
["class"] = "PALADIN",
["color"] = "200f09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F9",
["id"] = "Hammer of Wrath",
["class"] = "PALADIN",
["color"] = "0a5709",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F10",
["id"] = "Exorcism",
["class"] = "PALADIN",
["color"] = "4d4f08",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F11",
["id"] = "Crusader Strike",
["class"] = "PALADIN",
["color"] = "1f410a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-F12",
["id"] = "Holy Shield",
["class"] = "PALADIN",
["color"] = "17540a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-INSERT",
["id"] = "Avenger's Shield",
["class"] = "PALADIN",
["color"] = "18000a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DELETE",
["id"] = "Righteous Defense",
["class"] = "PALADIN",
["color"] = "1b150a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-HOME",
["id"] = "Blessing of Freedom",
["class"] = "PALADIN",
["color"] = "22270a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-END",
["id"] = "Blessing of Protection",
["class"] = "PALADIN",
["color"] = "0d440a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEUP",
["id"] = "Blessing of Sacrifice",
["class"] = "PALADIN",
["color"] = "121f0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-PAGEDOWN",
["id"] = "Divine Shield",
["class"] = "PALADIN",
["color"] = "252109",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-UP",
["id"] = "Divine Protection",
["class"] = "PALADIN",
["color"] = "434c09",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-DOWN",
["id"] = "Blessing of Kings",
["class"] = "PALADIN",
["color"] = "2a250a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-LEFT",
["id"] = "Blessing of Might",
["class"] = "PALADIN",
["color"] = "130e0a",
},
{
["type"] = "Dynamic",
["key"] = "CTRL-RIGHT",
["id"] = "Blessing of Wisdom",
["class"] = "PALADIN",
["color"] = "1e620a",
},
}
