warrior_binds = {
    # Racials
    # 'Shadowmeld': ('alt', 'shift', 'f1'),
    # 'Blood Fury': ('alt', 'shift', 'f1'),
    # 'Arcane Torrent': ('alt', 'shift', 'f1'),
    # 'Berserking': ('alt', 'shift', 'f1'),

    # Default
    'Auto Attack': 'home',
    'Stopcasting': 'insert',
    'player': ('alt', 'f2'),
    'party1': ('alt', 'f3'),
    'party2': ('alt', 'f5'),
    'party3': ('alt', 'f6'),
    'party4': ('alt', 'f7'),
    'raid1': ('ctrl', 'f1'),
    'raid2': ('ctrl', 'f2'),
    'raid3': ('ctrl', 'f3'),
    'raid4': ('ctrl', 'f4'),
    'raid5': ('ctrl', 'f5'),
    'raid6': ('ctrl', 'f6'),
    'raid7': ('ctrl', 'f7'),
    'raid8': ('ctrl', 'f8'),
    'raid9': ('ctrl', 'f9'),
    'raid10': ('ctrl', 'f10'),
    'raid11': ('ctrl', 'f11'),
    'raid12': ('ctrl', 'f12'),
    'raid13': ('shift', 'f1'),
    'raid14': ('shift', 'f2'),
    'raid15': ('shift', 'f3'),
    'raid16': ('shift', 'f4'),
    'raid17': ('shift', 'f5'),
    'raid18': ('shift', 'f6'),
    'raid19': ('shift', 'f7'),
    'raid20': ('shift', 'f8'),
    'raid21': ('shift', 'f9'),
    'raid22': ('shift', 'f10'),
    'raid23': ('shift', 'f11'),
    'raid24': ('shift', 'f12'),
    'raid25': ('alt', 'f1'),
    'arena1': ('alt', 'f8'),
    'arena2': ('alt', 'f9'),
    'arena3': ('alt', 'f10'),
    'arena4': ('alt', 'f11'),
    'arena5': ('alt', 'shift', 'f12'),
    'arenapet1': ('ctrl', 'shift', 'f1'),
    'arenapet2': ('ctrl', 'shift', 'f2'),
    'arenapet3': ('ctrl', 'shift', 'f3'),
    'arenapet4': ('ctrl', 'shift', 'f4'),
    'arenapet5': ('ctrl', 'shift', 'f5'),
    'clearfocus': 'delete',
    'target': ('alt', 'shift', 'f11'),

    # Priest
    'Flash Heal': ('ctrl', 'y'),
    'Power Word: Shield': ('ctrl', 'u'),
    'Shadow Word: Pain': ('ctrl', 'i'),
    'Mind Flay': ('ctrl', 'o'),
    'Mind Flay: Insanity': ('ctrl', 'o'),
    'Mind Blast': ('ctrl', 'p'),
    'Shadowform': ('ctrl', 'j'),
    'Shadow Word: Death': ('ctrl', 'k'),
    'Vampiric Touch': ('ctrl', 'l'),
    'Devouring Plague': ('ctrl', 'n'),
    'Power Word: Fortitude': ('ctrl', 'm'),
    'Angelic Feather': ('ctrl', '6'),
    'Desperate Prayer': ('ctrl', '7'),
    'Dispel Magic': ('ctrl', '8'),
    'Fade': ('ctrl', '9'),
    'Halo': ('ctrl', '0'),
    'Holy Nova': ('shift', 'y'),
    'Leap of Faith': ('shift', 'u'),
    'Levitate': ('shift', 'i'),
    'Mass Dispel': ('shift', 'o'),
    'Mind Control': ('shift', 'p'),
    'Mind Soothe': ('shift', 'j'),
    'Power Infusion': ('shift', 'k'),
    'Power Word: Life': ('shift', 'l'),
    'Psychic Scream': ('shift', 'n'),
    'fiend_fiend': ('shift', 'm'),
    'Vampiric Embrace': ('shift', '6'),
    'Void Shift': ('shift', '7'),
    'Void Tendrils': ('shift', '8'),
    'Shadow Crash': ('shift', '9'),
    'Silence': ('shift', '0'),
    'Dispersion': ('alt', 'y'),
    'Psychic Horror': ('alt', 'u'),
    'Psyfiend': ('alt', 'i'),
    'Void Eruption': ('alt', 'o'),
    'Void Torrent': ('alt', 'p'),
    'Void Bolt': ('alt', 'j'),
    'Mindgames': ('alt', 'k'),
    'Divine Star': ('alt', 'l'),
    'Dark Ascension': ('alt', 'n'),
    'Void Blast': ('alt', 'm'),
    # 'Revenge': ('alt', '6'),
    # 'Ignore Pain': ('alt', '7'),
    # 'Shield Charge': ('alt', '8'),
    # 'Piercing Howl': ('alt', '9'),
    # 'slam+heroic': ('alt', '0'),

    # Paladin
    'Gift of the Naaru(Racial)': ('ctrl', 'y'),
    'Blessing of Freedom': ('ctrl', 'u'),
    'Blessing of Sacrifice': ('ctrl', 'i'),
    'Blinding Light': ('ctrl', 'o'),
    'Concentration Aura': ('ctrl', 'p'),
    'Devotion Aura': ('ctrl', 'j'),
    'Divine Shield': ('ctrl', 'k'),
    'Divine Steed': ('ctrl', 'l'),
    'Divine Toll': ('ctrl', 'n'),
    'Flash of Light': ('ctrl', 'm'),
    'Hammer of Wrath': ('ctrl', '6'),
    'Hand of Reckoning': ('ctrl', '7'),
    'Judgment': ('ctrl', '8'),
    'Lay_on_Hands': ('ctrl', '9'),
    'Rebuke': ('ctrl', '0'),
    'Shield of the Righteous': ('shift', 'y'),
    'Word of Glory': ('shift', 'u'),
    'Blade of Justice': ('shift', 'i'),
    'Blessing of Sanctuary(PvP Talent)': ('shift', 'o'),
    'Blessing of Spellwarding': ('shift', 'p'),
    'Divine Storm': ('shift', 'j'),
    'Final Reckoning': ('shift', 'k'),
    'Final Verdict': ('shift', 'l'),
    'Shield of Vengeance': ('shift', 'n'),
    'Templar Strike': ('shift', 'm'),
    'Wake_of_Ashes': ('shift', '6'),
    # 'Void Shift': ('shift', '7'),
    # 'Void Tendrils': ('shift', '8'),
    # 'Shadow Crash': ('shift', '9'),
    # 'Silence': ('shift', '0'),
    # 'Dispersion': ('alt', 'y'),
    # 'Psychic Horror': ('alt', 'u'),
    # 'Psyfiend': ('alt', 'i'),
    # 'Void Eruption': ('alt', 'o'),
    # 'Void Torrent': ('alt', 'p'),
    # 'Void Bolt': ('alt', 'j'),
    # 'Mindgames': ('alt', 'k'),
    # 'Shadow Crash': ('alt', 'l'),
    # 'Void Eruption': ('alt', 'n'),
    # 'Void Bolt': ('alt', 'n'),
    # 'Enraged Regeneration': ('alt', 'm'),
    # 'Revenge': ('alt', '6'),
    # 'Ignore Pain': ('alt', '7'),
    # 'Shield Charge': ('alt', '8'),
    # 'Piercing Howl': ('alt', '9'),
    # 'slam+heroic': ('alt', '0'),

    # Druid
    'Shadowmeld(Racial)': ('ctrl', 'y'),
    'Barkskin': ('ctrl', 'u'),
    'Bear Form': ('ctrl', 'i'),
    'Cat Form': ('ctrl', 'o'),
    'Dash': ('ctrl', 'p'),
    'Entangling Roots': ('ctrl', 'j'),
    'Cyclone': ('ctrl', 'k'),
    'Ferocious Bite': ('ctrl', 'l'),
    # '': ('ctrl', 'n'),
    'Growl': ('ctrl', 'm'),
    'Heart of the Wild': ('ctrl', '6'),
    'Innervate': ('ctrl', '7'),
    'Ironfur': ('ctrl', '8'),
    'Mangle': ('ctrl', '9'),
    # '': ('ctrl', '0'),
    'Mass Entanglement': ('shift', 'y'),
    'Mighty Bash': ('shift', 'u'),
    'Moonfire': ('shift', 'i'),
    'Prowl': ('shift', 'o'),
    'Rake': ('shift', 'p'),
    'Regrowth': ('shift', 'j'),
    'Rejuvenation': ('shift', 'k'),
    'Renewal': ('shift', 'l'),
    'Shred': ('shift', 'n'),
    'Stampeding Roar': ('shift', 'm'),
    'Swipe': ('shift', '6'),
    'Travel Form': ('shift', '7'),
    'Wild Charge': ('shift', '8'),
    'Wild Growth': ('shift', '9'),
    'Wrath': ('shift', '0'),
    'Cenarion Ward': ('alt', 'y'),
    'Efflorescence': ('alt', 'u'),
    'Grove Guardians': ('alt', 'i'),
    'Incarnation: Tree of Life': ('alt', 'o'),
    'Ironbark': ('alt', 'p'),
    'Lifebloom': ('alt', 'j'),
    'Nature\'s Cure': ('alt', 'k'),
    'Nature\'s Swiftness': ('alt', 'l'),
    # '': ('alt', 'n'),
    'Swiftmend': ('alt', 'm'),
    'Tranquility': ('alt', '6'),
    # '': ('alt', '7'),
    'Over growth pls': ('alt', '8'),
    'Mark of the Wild': ('alt', '9'),
    'Frenz Regen': ('alt', '0'),
}
